// This file is auto-generated by @hey-api/openapi-ts

import type { CancelablePromise } from "./core/CancelablePromise"
import { OpenAPI } from "./core/OpenAPI"
import { request as __request } from "./core/request"
import type {
  ApplicationsListApplicationsEndpointResponse,
  ApplicationsSubmitApplicationEndpointData,
  ApplicationsSubmitApplicationEndpointResponse,
  ApplicationsGetApplicationEndpointData,
  ApplicationsGetApplicationEndpointResponse,
  FilesUploadFileAndCreateData,
  FilesUploadFileAndCreateResponse,
  FilesDownloadFileEndpointData,
  FilesDownloadFileEndpointResponse,
  FilesDeleteFileEndpointData,
  FilesDeleteFileEndpointResponse,
  ItemsReadItemsData,
  ItemsReadItemsResponse,
  ItemsCreateItemData,
  ItemsCreateItemResponse,
  ItemsReadItemData,
  ItemsReadItemResponse,
  ItemsUpdateItemData,
  ItemsUpdateItemResponse,
  ItemsDeleteItemData,
  ItemsDeleteItemResponse,
  JobsListJobListingsResponse,
  JobsCreateJobListingData,
  JobsCreateJobListingResponse,
  JobsParseJobListingData,
  JobsParseJobListingResponse,
  JobsParseJobListingFileData,
  JobsParseJobListingFileResponse,
  LoginLoginAccessTokenData,
  LoginLoginAccessTokenResponse,
  LoginTestTokenResponse,
  LoginRecoverPasswordData,
  LoginRecoverPasswordResponse,
  LoginResetPasswordData,
  LoginResetPasswordResponse,
  LoginRecoverPasswordHtmlContentData,
  LoginRecoverPasswordHtmlContentResponse,
  PrivateCreateUserData,
  PrivateCreateUserResponse,
  ResumesListResumesEndpointResponse,
  ResumesUploadResumeEndpointData,
  ResumesUploadResumeEndpointResponse,
  ResumesGetResumeEndpointData,
  ResumesGetResumeEndpointResponse,
  ResumesDeleteResumeEndpointData,
  ResumesDeleteResumeEndpointResponse,
  ScreensListScreensEndpointResponse,
  ScreensCreateScreenEndpointData,
  ScreensCreateScreenEndpointResponse,
  ScreensGetScreenEndpointData,
  ScreensGetScreenEndpointResponse,
  UsersReadUsersData,
  UsersReadUsersResponse,
  UsersCreateUserData,
  UsersCreateUserResponse,
  UsersReadUserMeResponse,
  UsersDeleteUserMeResponse,
  UsersUpdateUserMeData,
  UsersUpdateUserMeResponse,
  UsersUpdatePasswordMeData,
  UsersUpdatePasswordMeResponse,
  UsersRegisterUserData,
  UsersRegisterUserResponse,
  UsersReadUserByIdData,
  UsersReadUserByIdResponse,
  UsersUpdateUserData,
  UsersUpdateUserResponse,
  UsersDeleteUserData,
  UsersDeleteUserResponse,
  UtilsTestEmailData,
  UtilsTestEmailResponse,
  UtilsHealthCheckResponse,
} from "./types.gen"

export class ApplicationsService {
  /**
   * List Applications Endpoint
   * List job applications visible to the current user.
   * @returns JobApplicationRead Successful Response
   * @throws ApiError
   */
  public static listApplicationsEndpoint(): CancelablePromise<ApplicationsListApplicationsEndpointResponse> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/api/v1/applications",
    })
  }

  /**
   * Submit Application Endpoint
   * Submit a job application on behalf of the current user.
   * @param data The data for the request.
   * @param data.requestBody
   * @returns JobApplicationRead Successful Response
   * @throws ApiError
   */
  public static submitApplicationEndpoint(
    data: ApplicationsSubmitApplicationEndpointData,
  ): CancelablePromise<ApplicationsSubmitApplicationEndpointResponse> {
    return __request(OpenAPI, {
      method: "POST",
      url: "/api/v1/applications",
      body: data.requestBody,
      mediaType: "application/json",
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Get Application Endpoint
   * Retrieve a single job application if authorized.
   * @param data The data for the request.
   * @param data.applicationId
   * @returns JobApplicationRead Successful Response
   * @throws ApiError
   */
  public static getApplicationEndpoint(
    data: ApplicationsGetApplicationEndpointData,
  ): CancelablePromise<ApplicationsGetApplicationEndpointResponse> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/api/v1/applications/{application_id}",
      path: {
        application_id: data.applicationId,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }
}

export class FilesService {
  /**
   * Upload File And Create
   * Handles file upload, delegates storage, and records metadata in the database.
   * @param data The data for the request.
   * @param data.formData
   * @returns File Successful Response
   * @throws ApiError
   */
  public static uploadFileAndCreate(
    data: FilesUploadFileAndCreateData,
  ): CancelablePromise<FilesUploadFileAndCreateResponse> {
    return __request(OpenAPI, {
      method: "POST",
      url: "/api/v1/files",
      formData: data.formData,
      mediaType: "multipart/form-data",
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Download File Endpoint
   * Retrieves a file by its database ID, performs authorization, and streams the content.
   * @param data The data for the request.
   * @param data.fileId
   * @returns unknown Successful Response
   * @throws ApiError
   */
  public static downloadFileEndpoint(
    data: FilesDownloadFileEndpointData,
  ): CancelablePromise<FilesDownloadFileEndpointResponse> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/api/v1/files/{file_id}",
      path: {
        file_id: data.fileId,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Delete File Endpoint
   * Deletes file metadata from the database and removes the file from storage.
   * Only the owner or a superuser is authorized.
   * @param data The data for the request.
   * @param data.fileId
   * @returns void Successful Response
   * @throws ApiError
   */
  public static deleteFileEndpoint(
    data: FilesDeleteFileEndpointData,
  ): CancelablePromise<FilesDeleteFileEndpointResponse> {
    return __request(OpenAPI, {
      method: "DELETE",
      url: "/api/v1/files/{file_id}",
      path: {
        file_id: data.fileId,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }
}

export class ItemsService {
  /**
   * Read Items
   * Retrieve items.
   * @param data The data for the request.
   * @param data.skip
   * @param data.limit
   * @returns ItemsPublic Successful Response
   * @throws ApiError
   */
  public static readItems(
    data: ItemsReadItemsData = {},
  ): CancelablePromise<ItemsReadItemsResponse> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/api/v1/items/",
      query: {
        skip: data.skip,
        limit: data.limit,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Create Item
   * Create new item.
   * @param data The data for the request.
   * @param data.requestBody
   * @returns ItemPublic Successful Response
   * @throws ApiError
   */
  public static createItem(
    data: ItemsCreateItemData,
  ): CancelablePromise<ItemsCreateItemResponse> {
    return __request(OpenAPI, {
      method: "POST",
      url: "/api/v1/items/",
      body: data.requestBody,
      mediaType: "application/json",
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Read Item
   * Get item by ID.
   * @param data The data for the request.
   * @param data.id
   * @returns ItemPublic Successful Response
   * @throws ApiError
   */
  public static readItem(
    data: ItemsReadItemData,
  ): CancelablePromise<ItemsReadItemResponse> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/api/v1/items/{id}",
      path: {
        id: data.id,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Update Item
   * Update an item.
   * @param data The data for the request.
   * @param data.id
   * @param data.requestBody
   * @returns ItemPublic Successful Response
   * @throws ApiError
   */
  public static updateItem(
    data: ItemsUpdateItemData,
  ): CancelablePromise<ItemsUpdateItemResponse> {
    return __request(OpenAPI, {
      method: "PUT",
      url: "/api/v1/items/{id}",
      path: {
        id: data.id,
      },
      body: data.requestBody,
      mediaType: "application/json",
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Delete Item
   * Delete an item.
   * @param data The data for the request.
   * @param data.id
   * @returns Message Successful Response
   * @throws ApiError
   */
  public static deleteItem(
    data: ItemsDeleteItemData,
  ): CancelablePromise<ItemsDeleteItemResponse> {
    return __request(OpenAPI, {
      method: "DELETE",
      url: "/api/v1/items/{id}",
      path: {
        id: data.id,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }
}

export class JobsService {
  /**
   * List Job Listings
   * Retrieve all job listings, newest first.
   * @returns JobListingRead Successful Response
   * @throws ApiError
   */
  public static listJobListings(): CancelablePromise<JobsListJobListingsResponse> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/api/v1/jobs/listings",
    })
  }

  /**
   * Create Job Listing
   * Persist a structured job listing record.
   * @param data The data for the request.
   * @param data.requestBody
   * @returns JobListingRead Successful Response
   * @throws ApiError
   */
  public static createJobListing(
    data: JobsCreateJobListingData,
  ): CancelablePromise<JobsCreateJobListingResponse> {
    return __request(OpenAPI, {
      method: "POST",
      url: "/api/v1/jobs/listings",
      body: data.requestBody,
      mediaType: "application/json",
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Parse Job Listing
   * Parse raw job listing text into structured data using the LLM agent.
   * @param data The data for the request.
   * @param data.requestBody
   * @returns JobListingParseResponse Successful Response
   * @throws ApiError
   */
  public static parseJobListing(
    data: JobsParseJobListingData,
  ): CancelablePromise<JobsParseJobListingResponse> {
    return __request(OpenAPI, {
      method: "POST",
      url: "/api/v1/jobs/listings/parse",
      body: data.requestBody,
      mediaType: "application/json",
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Parse Job Listing File
   * Parse an uploaded document into a structured job listing via the LLM agent.
   * @param data The data for the request.
   * @param data.formData
   * @returns JobListingParseResponse Successful Response
   * @throws ApiError
   */
  public static parseJobListingFile(
    data: JobsParseJobListingFileData,
  ): CancelablePromise<JobsParseJobListingFileResponse> {
    return __request(OpenAPI, {
      method: "POST",
      url: "/api/v1/jobs/listings/parse-file",
      formData: data.formData,
      mediaType: "multipart/form-data",
      errors: {
        422: "Validation Error",
      },
    })
  }
}

export class LoginService {
  /**
   * Login Access Token
   * OAuth2 compatible token login, get an access token for future requests
   * @param data The data for the request.
   * @param data.formData
   * @returns Token Successful Response
   * @throws ApiError
   */
  public static loginAccessToken(
    data: LoginLoginAccessTokenData,
  ): CancelablePromise<LoginLoginAccessTokenResponse> {
    return __request(OpenAPI, {
      method: "POST",
      url: "/api/v1/login/access-token",
      formData: data.formData,
      mediaType: "application/x-www-form-urlencoded",
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Test Token
   * Test access token
   * @returns UserPublic Successful Response
   * @throws ApiError
   */
  public static testToken(): CancelablePromise<LoginTestTokenResponse> {
    return __request(OpenAPI, {
      method: "POST",
      url: "/api/v1/login/test-token",
    })
  }

  /**
   * Recover Password
   * Password Recovery
   * @param data The data for the request.
   * @param data.email
   * @returns Message Successful Response
   * @throws ApiError
   */
  public static recoverPassword(
    data: LoginRecoverPasswordData,
  ): CancelablePromise<LoginRecoverPasswordResponse> {
    return __request(OpenAPI, {
      method: "POST",
      url: "/api/v1/password-recovery/{email}",
      path: {
        email: data.email,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Reset Password
   * Reset password
   * @param data The data for the request.
   * @param data.requestBody
   * @returns Message Successful Response
   * @throws ApiError
   */
  public static resetPassword(
    data: LoginResetPasswordData,
  ): CancelablePromise<LoginResetPasswordResponse> {
    return __request(OpenAPI, {
      method: "POST",
      url: "/api/v1/reset-password/",
      body: data.requestBody,
      mediaType: "application/json",
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Recover Password Html Content
   * HTML Content for Password Recovery
   * @param data The data for the request.
   * @param data.email
   * @returns string Successful Response
   * @throws ApiError
   */
  public static recoverPasswordHtmlContent(
    data: LoginRecoverPasswordHtmlContentData,
  ): CancelablePromise<LoginRecoverPasswordHtmlContentResponse> {
    return __request(OpenAPI, {
      method: "POST",
      url: "/api/v1/password-recovery-html-content/{email}",
      path: {
        email: data.email,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }
}

export class PrivateService {
  /**
   * Create User
   * Create a new user.
   * @param data The data for the request.
   * @param data.requestBody
   * @returns UserPublic Successful Response
   * @throws ApiError
   */
  public static createUser(
    data: PrivateCreateUserData,
  ): CancelablePromise<PrivateCreateUserResponse> {
    return __request(OpenAPI, {
      method: "POST",
      url: "/api/v1/private/users/",
      body: data.requestBody,
      mediaType: "application/json",
      errors: {
        422: "Validation Error",
      },
    })
  }
}

export class ResumesService {
  /**
   * List Resumes Endpoint
   * Return resumes accessible to the current user.
   * @returns ResumeRead Successful Response
   * @throws ApiError
   */
  public static listResumesEndpoint(): CancelablePromise<ResumesListResumesEndpointResponse> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/api/v1/resumes",
    })
  }

  /**
   * Upload Resume Endpoint
   * Upload a resume, persist the file, and store parsed text content.
   * @param data The data for the request.
   * @param data.formData
   * @returns ResumeRead Successful Response
   * @throws ApiError
   */
  public static uploadResumeEndpoint(
    data: ResumesUploadResumeEndpointData,
  ): CancelablePromise<ResumesUploadResumeEndpointResponse> {
    return __request(OpenAPI, {
      method: "POST",
      url: "/api/v1/resumes",
      formData: data.formData,
      mediaType: "multipart/form-data",
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Get Resume Endpoint
   * Return a single resume if the requester is authorized.
   * @param data The data for the request.
   * @param data.resumeId
   * @returns ResumeRead Successful Response
   * @throws ApiError
   */
  public static getResumeEndpoint(
    data: ResumesGetResumeEndpointData,
  ): CancelablePromise<ResumesGetResumeEndpointResponse> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/api/v1/resumes/{resume_id}",
      path: {
        resume_id: data.resumeId,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Delete Resume Endpoint
   * Delete a resume and its backing file if authorized.
   * @param data The data for the request.
   * @param data.resumeId
   * @returns void Successful Response
   * @throws ApiError
   */
  public static deleteResumeEndpoint(
    data: ResumesDeleteResumeEndpointData,
  ): CancelablePromise<ResumesDeleteResumeEndpointResponse> {
    return __request(OpenAPI, {
      method: "DELETE",
      url: "/api/v1/resumes/{resume_id}",
      path: {
        resume_id: data.resumeId,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }
}

export class ScreensService {
  /**
   * List Screens Endpoint
   * Return screening results visible to the current user.
   * @returns JobApplicationScreenRead Successful Response
   * @throws ApiError
   */
  public static listScreensEndpoint(): CancelablePromise<ScreensListScreensEndpointResponse> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/api/v1/screens",
    })
  }

  /**
   * Create Screen Endpoint
   * Screen a job application against its listing.
   * @param data The data for the request.
   * @param data.requestBody
   * @returns JobApplicationScreenRead Successful Response
   * @throws ApiError
   */
  public static createScreenEndpoint(
    data: ScreensCreateScreenEndpointData,
  ): CancelablePromise<ScreensCreateScreenEndpointResponse> {
    return __request(OpenAPI, {
      method: "POST",
      url: "/api/v1/screens",
      body: data.requestBody,
      mediaType: "application/json",
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Get Screen Endpoint
   * Retrieve a screening result if the requester is authorized.
   * @param data The data for the request.
   * @param data.screenId
   * @returns JobApplicationScreenRead Successful Response
   * @throws ApiError
   */
  public static getScreenEndpoint(
    data: ScreensGetScreenEndpointData,
  ): CancelablePromise<ScreensGetScreenEndpointResponse> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/api/v1/screens/{screen_id}",
      path: {
        screen_id: data.screenId,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }
}

export class UsersService {
  /**
   * Read Users
   * Retrieve users.
   * @param data The data for the request.
   * @param data.skip
   * @param data.limit
   * @returns UsersPublic Successful Response
   * @throws ApiError
   */
  public static readUsers(
    data: UsersReadUsersData = {},
  ): CancelablePromise<UsersReadUsersResponse> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/api/v1/users/",
      query: {
        skip: data.skip,
        limit: data.limit,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Create User
   * Create new user.
   * @param data The data for the request.
   * @param data.requestBody
   * @returns UserPublic Successful Response
   * @throws ApiError
   */
  public static createUser(
    data: UsersCreateUserData,
  ): CancelablePromise<UsersCreateUserResponse> {
    return __request(OpenAPI, {
      method: "POST",
      url: "/api/v1/users/",
      body: data.requestBody,
      mediaType: "application/json",
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Read User Me
   * Get current user.
   * @returns UserPublic Successful Response
   * @throws ApiError
   */
  public static readUserMe(): CancelablePromise<UsersReadUserMeResponse> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/api/v1/users/me",
    })
  }

  /**
   * Delete User Me
   * Delete own user.
   * @returns Message Successful Response
   * @throws ApiError
   */
  public static deleteUserMe(): CancelablePromise<UsersDeleteUserMeResponse> {
    return __request(OpenAPI, {
      method: "DELETE",
      url: "/api/v1/users/me",
    })
  }

  /**
   * Update User Me
   * Update own user.
   * @param data The data for the request.
   * @param data.requestBody
   * @returns UserPublic Successful Response
   * @throws ApiError
   */
  public static updateUserMe(
    data: UsersUpdateUserMeData,
  ): CancelablePromise<UsersUpdateUserMeResponse> {
    return __request(OpenAPI, {
      method: "PATCH",
      url: "/api/v1/users/me",
      body: data.requestBody,
      mediaType: "application/json",
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Update Password Me
   * Update own password.
   * @param data The data for the request.
   * @param data.requestBody
   * @returns Message Successful Response
   * @throws ApiError
   */
  public static updatePasswordMe(
    data: UsersUpdatePasswordMeData,
  ): CancelablePromise<UsersUpdatePasswordMeResponse> {
    return __request(OpenAPI, {
      method: "PATCH",
      url: "/api/v1/users/me/password",
      body: data.requestBody,
      mediaType: "application/json",
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Register User
   * Create new user without the need to be logged in.
   * @param data The data for the request.
   * @param data.requestBody
   * @returns UserPublic Successful Response
   * @throws ApiError
   */
  public static registerUser(
    data: UsersRegisterUserData,
  ): CancelablePromise<UsersRegisterUserResponse> {
    return __request(OpenAPI, {
      method: "POST",
      url: "/api/v1/users/signup",
      body: data.requestBody,
      mediaType: "application/json",
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Read User By Id
   * Get a specific user by id.
   * @param data The data for the request.
   * @param data.userId
   * @returns UserPublic Successful Response
   * @throws ApiError
   */
  public static readUserById(
    data: UsersReadUserByIdData,
  ): CancelablePromise<UsersReadUserByIdResponse> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/api/v1/users/{user_id}",
      path: {
        user_id: data.userId,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Update User
   * Update a user.
   * @param data The data for the request.
   * @param data.userId
   * @param data.requestBody
   * @returns UserPublic Successful Response
   * @throws ApiError
   */
  public static updateUser(
    data: UsersUpdateUserData,
  ): CancelablePromise<UsersUpdateUserResponse> {
    return __request(OpenAPI, {
      method: "PATCH",
      url: "/api/v1/users/{user_id}",
      path: {
        user_id: data.userId,
      },
      body: data.requestBody,
      mediaType: "application/json",
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Delete User
   * Delete a user.
   * @param data The data for the request.
   * @param data.userId
   * @returns Message Successful Response
   * @throws ApiError
   */
  public static deleteUser(
    data: UsersDeleteUserData,
  ): CancelablePromise<UsersDeleteUserResponse> {
    return __request(OpenAPI, {
      method: "DELETE",
      url: "/api/v1/users/{user_id}",
      path: {
        user_id: data.userId,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }
}

export class UtilsService {
  /**
   * Test Email
   * Test emails.
   * @param data The data for the request.
   * @param data.emailTo
   * @returns Message Successful Response
   * @throws ApiError
   */
  public static testEmail(
    data: UtilsTestEmailData,
  ): CancelablePromise<UtilsTestEmailResponse> {
    return __request(OpenAPI, {
      method: "POST",
      url: "/api/v1/utils/test-email/",
      query: {
        email_to: data.emailTo,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Health Check
   * @returns boolean Successful Response
   * @throws ApiError
   */
  public static healthCheck(): CancelablePromise<UtilsHealthCheckResponse> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/api/v1/utils/health-check/",
    })
  }
}
