// This file is auto-generated by @hey-api/openapi-ts

export type Body_files_upload_file_and_create = {
  file: Blob | File
}

export type Body_jobs_parse_job_listing_file = {
  file: Blob | File
}

export type Body_login_login_access_token = {
  grant_type?: string | null
  username: string
  password: string
  scope?: string
  client_id?: string | null
  client_secret?: string | null
}

export type Body_resumes_upload_resume_endpoint = {
  file: Blob | File
}

/**
 * Database model for file metadata.
 */
export type File = {
  filename: string
  content_type: string
  size_bytes: number
  storage_key: string
  owner_id: string
  id?: string
  created_at?: string
  updated_at?: string
}

export type HTTPValidationError = {
  detail?: Array<ValidationError>
}

export type ItemCreate = {
  title: string
  description?: string | null
}

export type ItemPublic = {
  title: string
  description?: string | null
  id: string
  owner_id: string
}

export type ItemsPublic = {
  data: Array<ItemPublic>
  count: number
}

export type ItemUpdate = {
  title?: string | null
  description?: string | null
}

/**
 * Payload for submitting a job application.
 */
export type JobApplicationCreate = {
  job_listing_id: string
  resume_id?: string | null
  cover_letter?: string | null
}

/**
 * Public representation of a job application.
 */
export type JobApplicationRead = {
  job_listing_id: string
  resume_id?: string | null
  cover_letter?: string | null
  id: string
  applicant_id: string
  status: JobApplicationStatusEnum
  created_at: string
  updated_at: string
  applicant: UserPublic
  resume: ResumeRead | null
}

/**
 * Request payload to trigger a screening.
 */
export type JobApplicationScreenCreate = {
  application_id: string
}

/**
 * Public representation of screening results.
 */
export type JobApplicationScreenRead = {
  application_id: string
  minimum_qualifications?: Array<ScreeningReason>
  preferred_qualifications?: Array<ScreeningReason>
  id: string
  created_at: string
  updated_at: string
}

/**
 * Lifecycle states for a job application.
 */
export type JobApplicationStatusEnum =
  | "SUBMITTED"
  | "UNDER_REVIEW"
  | "REJECTED"
  | "WITHDRAWN"

/**
 * Data required to create a new job listing.
 */
export type JobListingCreate = {
  title: string
  description: string
  job_type?: JobTypeEnum
  minimum_qualifications?: Array<string>
  preferred_qualifications?: Array<string>
  company_name: string
  location: string
  is_remote?: boolean
  salary_min?: number | string | null
  salary_max?: number | string | null
  expires_on?: string | null
  is_active?: boolean
}

/**
 * Request payload for parsing raw job listing text.
 */
export type JobListingParseRequest = {
  text: string
}

export type JobListingParseResponse = {
  title?: string
  description?: string
  job_type?: JobTypeEnum
  minimum_qualifications?: Array<string>
  preferred_qualifications?: Array<string>
  company_name?: string
  location?: string
  is_remote?: boolean
  salary_min?: string | null
  salary_max?: string | null
  expires_on?: string | null
  is_active?: boolean
}

/**
 * Public representation of a job listing.
 */
export type JobListingRead = {
  title: string
  description: string
  job_type?: JobTypeEnum
  minimum_qualifications?: Array<string>
  preferred_qualifications?: Array<string>
  company_name: string
  location: string
  is_remote?: boolean
  salary_min?: string | null
  salary_max?: string | null
  expires_on?: string | null
  is_active?: boolean
  id: string
  company_id: string
  posted_on: string
}

/**
 * Employment type codes.
 */
export type JobTypeEnum = "FT" | "PT" | "CO" | "IN" | "TE"

export type Message = {
  message: string
}

export type NewPassword = {
  token: string
  new_password: string
}

export type PrivateUserCreate = {
  email: string
  password: string
  full_name: string
  is_verified?: boolean
}

/**
 * Public representation of a resume record.
 */
export type ResumeRead = {
  user_id: string
  file_id: string
  text_content?: string
  id: string
  created_at: string
  updated_at: string
}

/**
 * Explains how a qualification was evaluated.
 */
export type ScreeningReason = {
  status: ScreeningReasonStatusEnum
  reason: string
}

/**
 * Qualification match status.
 */
export type ScreeningReasonStatusEnum =
  | "HIGHLY_QUALIFIED"
  | "QUALIFIED"
  | "MEETS"
  | "NOT_QUALIFIED"

export type Token = {
  access_token: string
  token_type?: string
}

export type UpdatePassword = {
  current_password: string
  new_password: string
}

export type UserCreate = {
  email: string
  is_active?: boolean
  is_superuser?: boolean
  full_name?: string | null
  role?: UserRoleEnum
  password: string
}

export type UserPublic = {
  email: string
  is_active?: boolean
  is_superuser?: boolean
  full_name?: string | null
  role?: UserRoleEnum
  id: string
}

export type UserRegister = {
  email: string
  password: string
  full_name?: string | null
  role?: UserRoleEnum
}

export type UserRoleEnum = "COMPANY" | "APPLICANT"

export type UsersPublic = {
  data: Array<UserPublic>
  count: number
}

export type UserUpdate = {
  email?: string | null
  is_active?: boolean
  is_superuser?: boolean
  full_name?: string | null
  role?: UserRoleEnum | null
  password?: string | null
}

export type UserUpdateMe = {
  full_name?: string | null
  email?: string | null
}

export type ValidationError = {
  loc: Array<string | number>
  msg: string
  type: string
}

export type ApplicationsListApplicationsEndpointResponse =
  Array<JobApplicationRead>

export type ApplicationsSubmitApplicationEndpointData = {
  requestBody: JobApplicationCreate
}

export type ApplicationsSubmitApplicationEndpointResponse = JobApplicationRead

export type ApplicationsGetApplicationEndpointData = {
  applicationId: string
}

export type ApplicationsGetApplicationEndpointResponse = JobApplicationRead

export type FilesUploadFileAndCreateData = {
  formData: Body_files_upload_file_and_create
}

export type FilesUploadFileAndCreateResponse = File

export type FilesDownloadFileEndpointData = {
  fileId: string
}

export type FilesDownloadFileEndpointResponse = unknown

export type FilesDeleteFileEndpointData = {
  fileId: string
}

export type FilesDeleteFileEndpointResponse = void

export type ItemsReadItemsData = {
  limit?: number
  skip?: number
}

export type ItemsReadItemsResponse = ItemsPublic

export type ItemsCreateItemData = {
  requestBody: ItemCreate
}

export type ItemsCreateItemResponse = ItemPublic

export type ItemsReadItemData = {
  id: string
}

export type ItemsReadItemResponse = ItemPublic

export type ItemsUpdateItemData = {
  id: string
  requestBody: ItemUpdate
}

export type ItemsUpdateItemResponse = ItemPublic

export type ItemsDeleteItemData = {
  id: string
}

export type ItemsDeleteItemResponse = Message

export type JobsListJobListingsResponse = Array<JobListingRead>

export type JobsCreateJobListingData = {
  requestBody: JobListingCreate
}

export type JobsCreateJobListingResponse = JobListingRead

export type JobsParseJobListingData = {
  requestBody: JobListingParseRequest
}

export type JobsParseJobListingResponse = JobListingParseResponse

export type JobsParseJobListingFileData = {
  formData: Body_jobs_parse_job_listing_file
}

export type JobsParseJobListingFileResponse = JobListingParseResponse

export type LoginLoginAccessTokenData = {
  formData: Body_login_login_access_token
}

export type LoginLoginAccessTokenResponse = Token

export type LoginTestTokenResponse = UserPublic

export type LoginRecoverPasswordData = {
  email: string
}

export type LoginRecoverPasswordResponse = Message

export type LoginResetPasswordData = {
  requestBody: NewPassword
}

export type LoginResetPasswordResponse = Message

export type LoginRecoverPasswordHtmlContentData = {
  email: string
}

export type LoginRecoverPasswordHtmlContentResponse = string

export type PrivateCreateUserData = {
  requestBody: PrivateUserCreate
}

export type PrivateCreateUserResponse = UserPublic

export type ResumesListResumesEndpointResponse = Array<ResumeRead>

export type ResumesUploadResumeEndpointData = {
  formData: Body_resumes_upload_resume_endpoint
}

export type ResumesUploadResumeEndpointResponse = ResumeRead

export type ResumesGetResumeEndpointData = {
  resumeId: string
}

export type ResumesGetResumeEndpointResponse = ResumeRead

export type ResumesDeleteResumeEndpointData = {
  resumeId: string
}

export type ResumesDeleteResumeEndpointResponse = void

export type ScreensListScreensEndpointResponse = Array<JobApplicationScreenRead>

export type ScreensCreateScreenEndpointData = {
  requestBody: JobApplicationScreenCreate
}

export type ScreensCreateScreenEndpointResponse = JobApplicationScreenRead

export type ScreensGetScreenEndpointData = {
  screenId: string
}

export type ScreensGetScreenEndpointResponse = JobApplicationScreenRead

export type UsersReadUsersData = {
  limit?: number
  skip?: number
}

export type UsersReadUsersResponse = UsersPublic

export type UsersCreateUserData = {
  requestBody: UserCreate
}

export type UsersCreateUserResponse = UserPublic

export type UsersReadUserMeResponse = UserPublic

export type UsersDeleteUserMeResponse = Message

export type UsersUpdateUserMeData = {
  requestBody: UserUpdateMe
}

export type UsersUpdateUserMeResponse = UserPublic

export type UsersUpdatePasswordMeData = {
  requestBody: UpdatePassword
}

export type UsersUpdatePasswordMeResponse = Message

export type UsersRegisterUserData = {
  requestBody: UserRegister
}

export type UsersRegisterUserResponse = UserPublic

export type UsersReadUserByIdData = {
  userId: string
}

export type UsersReadUserByIdResponse = UserPublic

export type UsersUpdateUserData = {
  requestBody: UserUpdate
  userId: string
}

export type UsersUpdateUserResponse = UserPublic

export type UsersDeleteUserData = {
  userId: string
}

export type UsersDeleteUserResponse = Message

export type UtilsTestEmailData = {
  emailTo: string
}

export type UtilsTestEmailResponse = Message

export type UtilsHealthCheckResponse = boolean
