"""test2

Revision ID: 113c78a2c928
Revises: 6a7b12e7e201
Create Date: 2025-11-14 22:16:21.824521

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from alembic_postgresql_enum import TableReference

# revision identifiers, used by Alembic.
revision = '113c78a2c928'
down_revision = '6a7b12e7e201'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values(
        enum_schema='public',
        enum_name='job_application_status_enum',
        new_values=['SUBMITTED', 'UNDER_REVIEW', 'INTERVIEW', 'ACCEPTED', 'REJECTED', 'WITHDRAWN', 'TEST'],
        affected_columns=[TableReference(table_schema='public', table_name='job_application', column_name='status')],
        enum_values_to_rename=[],
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values(
        enum_schema='public',
        enum_name='job_application_status_enum',
        new_values=['SUBMITTED', 'UNDER_REVIEW', 'REJECTED', 'WITHDRAWN'],
        affected_columns=[TableReference(table_schema='public', table_name='job_application', column_name='status')],
        enum_values_to_rename=[],
    )
    # ### end Alembic commands ###
