"""make job company mandatory

Revision ID: 3e6e54ee94ca
Revises: d9945b1c1523
Create Date: 2025-10-25 01:31:21.161616

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '3e6e54ee94ca'
down_revision = 'd9945b1c1523'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'job_listing',
        'company_id',
        existing_type=sa.Uuid(),
        nullable=False,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'job_listing',
        'company_id',
        existing_type=sa.Uuid(),
        nullable=True,
    )
    # ### end Alembic commands ###
