"""test

Revision ID: 6a7b12e7e201
Revises: 7f7af6e772a7
Create Date: 2025-11-14 21:47:15.524240

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '6a7b12e7e201'
down_revision = '7f7af6e772a7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
