"""add score to job application screen

Revision ID: 7f7af6e772a7
Revises: 3f73820144a3
Create Date: 2025-11-14 20:50:02.039040

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '7f7af6e772a7'
down_revision = '3f73820144a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job_application_screen', sa.Column('score', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('job_application_screen', 'score')
    # ### end Alembic commands ###
