"""add user role

Revision ID: 92266945935e
Revises: 0a5dd082b7ea
Create Date: 2025-10-25 00:57:53.707381

"""
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from alembic import op


# revision identifiers, used by Alembic.
revision = '92266945935e'
down_revision = '0a5dd082b7ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    user_role_enum = sa.Enum('COMPANY', 'APPLICANT', name='userroleenum')
    user_role_enum.create(op.get_bind(), checkfirst=True)
    op.add_column(
        'user',
        sa.Column(
            'role',
            user_role_enum,
            nullable=False,
            server_default='APPLICANT',
        ),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'role')
    sa.Enum(name='userroleenum').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
