"""add job applications

Revision ID: c0c0bab1dbfa
Revises: 9de8c6579f1f
Create Date: 2025-10-25 01:53:04.081899

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'c0c0bab1dbfa'
down_revision = '9de8c6579f1f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_application',
    sa.Column('job_listing_id', sa.Uuid(), nullable=False),
    sa.Column('resume_id', sa.Uuid(), nullable=True),
    sa.Column('cover_letter', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('applicant_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('SUBMITTED', 'UNDER_REVIEW', 'REJECTED', 'WITHDRAWN', name='job_application_status_enum'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['applicant_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['job_listing_id'], ['job_listing.id'], ),
    sa.ForeignKeyConstraint(['resume_id'], ['resume.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('job_listing_id', 'applicant_id', name='uq_job_application_listing_applicant')
    )
    op.create_index(op.f('ix_job_application_applicant_id'), 'job_application', ['applicant_id'], unique=False)
    op.create_index(op.f('ix_job_application_job_listing_id'), 'job_application', ['job_listing_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_job_application_job_listing_id'), table_name='job_application')
    op.drop_index(op.f('ix_job_application_applicant_id'), table_name='job_application')
    op.drop_table('job_application')
    # ### end Alembic commands ###
