"""change file id to uuid

Revision ID: d913f35aac54
Revises: f4e4340fff99
Create Date: 2025-10-24 20:31:53.996119

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = 'd913f35aac54'
down_revision = 'f4e4340fff99'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('CREATE EXTENSION IF NOT EXISTS "uuid-ossp"')
    op.execute('ALTER TABLE file ALTER COLUMN id DROP DEFAULT')
    op.alter_column('file', 'owner_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_constraint('file_pkey', 'file', type_='primary')
    op.execute('DROP SEQUENCE IF EXISTS file_id_seq')
    op.drop_column('file', 'id')
    op.add_column('file', sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False, server_default=sa.text('uuid_generate_v4()')))
    op.create_primary_key('file_pkey', 'file', ['id'])
    op.alter_column('file', 'id', server_default=None, existing_type=postgresql.UUID(as_uuid=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('file_pkey', 'file', type_='primary')
    op.drop_column('file', 'id')
    op.execute('CREATE SEQUENCE file_id_seq')
    op.add_column('file', sa.Column('id', sa.Integer(), nullable=False, server_default=sa.text("nextval('file_id_seq'::regclass)")))
    op.execute("ALTER TABLE file ALTER COLUMN id SET DEFAULT nextval('file_id_seq')")
    op.alter_column('file', 'owner_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.create_primary_key('file_pkey', 'file', ['id'])
    op.execute("ALTER SEQUENCE file_id_seq OWNED BY file.id")
    op.alter_column('file', 'id', server_default=None, existing_type=sa.Integer())
    # ### end Alembic commands ###
