"""add job company link

Revision ID: d9945b1c1523
Revises: 92266945935e
Create Date: 2025-10-25 01:24:41.048327

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'd9945b1c1523'
down_revision = '92266945935e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job_listing', sa.Column('company_id', sa.Uuid(), nullable=True))
    op.create_index(op.f('ix_job_listing_company_id'), 'job_listing', ['company_id'], unique=False)
    op.create_foreign_key(None, 'job_listing', 'user', ['company_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'job_listing', type_='foreignkey')
    op.drop_index(op.f('ix_job_listing_company_id'), table_name='job_listing')
    op.drop_column('job_listing', 'company_id')
    # ### end Alembic commands ###
