"""add job application screens

Revision ID: de3e7a3210ad
Revises: c0c0bab1dbfa
Create Date: 2025-10-25 02:10:17.310485

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'de3e7a3210ad'
down_revision = 'c0c0bab1dbfa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_application_screen',
    sa.Column('application_id', sa.Uuid(), nullable=False),
    sa.Column('minimum_qualifications', sa.JSON(), nullable=False),
    sa.Column('preferred_qualifications', sa.JSON(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['job_application.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('application_id', name='uq_job_application_screen_application')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('job_application_screen')
    # ### end Alembic commands ###
