/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as SignupImport } from './routes/signup'
import { Route as ResetPasswordImport } from './routes/reset-password'
import { Route as RecoverPasswordImport } from './routes/recover-password'
import { Route as LoginImport } from './routes/login'
import { Route as LayoutImport } from './routes/_layout'
import { Route as LayoutIndexImport } from './routes/_layout/index'
import { Route as LayoutSettingsImport } from './routes/_layout/settings'
import { Route as LayoutScreensImport } from './routes/_layout/screens'
import { Route as LayoutResumesImport } from './routes/_layout/resumes'
import { Route as LayoutJobsImport } from './routes/_layout/jobs'
import { Route as LayoutApplicationsImport } from './routes/_layout/applications'
import { Route as LayoutAdminImport } from './routes/_layout/admin'
import { Route as LayoutApplicationsIndexImport } from './routes/_layout/applications/index'
import { Route as LayoutJobJobIdImport } from './routes/_layout/job/$jobId'
import { Route as LayoutApplicationsApplicationIdImport } from './routes/_layout/applications/$applicationId'

// Create/Update Routes

const SignupRoute = SignupImport.update({
  path: '/signup',
  getParentRoute: () => rootRoute,
} as any)

const ResetPasswordRoute = ResetPasswordImport.update({
  path: '/reset-password',
  getParentRoute: () => rootRoute,
} as any)

const RecoverPasswordRoute = RecoverPasswordImport.update({
  path: '/recover-password',
  getParentRoute: () => rootRoute,
} as any)

const LoginRoute = LoginImport.update({
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const LayoutRoute = LayoutImport.update({
  id: '/_layout',
  getParentRoute: () => rootRoute,
} as any)

const LayoutIndexRoute = LayoutIndexImport.update({
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutSettingsRoute = LayoutSettingsImport.update({
  path: '/settings',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutScreensRoute = LayoutScreensImport.update({
  path: '/screens',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutResumesRoute = LayoutResumesImport.update({
  path: '/resumes',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutJobsRoute = LayoutJobsImport.update({
  path: '/jobs',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutApplicationsRoute = LayoutApplicationsImport.update({
  path: '/applications',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutAdminRoute = LayoutAdminImport.update({
  path: '/admin',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutApplicationsIndexRoute = LayoutApplicationsIndexImport.update({
  path: '/',
  getParentRoute: () => LayoutApplicationsRoute,
} as any)

const LayoutJobJobIdRoute = LayoutJobJobIdImport.update({
  path: '/job/$jobId',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutApplicationsApplicationIdRoute =
  LayoutApplicationsApplicationIdImport.update({
    path: '/$applicationId',
    getParentRoute: () => LayoutApplicationsRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_layout': {
      preLoaderRoute: typeof LayoutImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      preLoaderRoute: typeof LoginImport
      parentRoute: typeof rootRoute
    }
    '/recover-password': {
      preLoaderRoute: typeof RecoverPasswordImport
      parentRoute: typeof rootRoute
    }
    '/reset-password': {
      preLoaderRoute: typeof ResetPasswordImport
      parentRoute: typeof rootRoute
    }
    '/signup': {
      preLoaderRoute: typeof SignupImport
      parentRoute: typeof rootRoute
    }
    '/_layout/admin': {
      preLoaderRoute: typeof LayoutAdminImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/applications': {
      preLoaderRoute: typeof LayoutApplicationsImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/jobs': {
      preLoaderRoute: typeof LayoutJobsImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/resumes': {
      preLoaderRoute: typeof LayoutResumesImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/screens': {
      preLoaderRoute: typeof LayoutScreensImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/settings': {
      preLoaderRoute: typeof LayoutSettingsImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/': {
      preLoaderRoute: typeof LayoutIndexImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/applications/$applicationId': {
      preLoaderRoute: typeof LayoutApplicationsApplicationIdImport
      parentRoute: typeof LayoutApplicationsImport
    }
    '/_layout/job/$jobId': {
      preLoaderRoute: typeof LayoutJobJobIdImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/applications/': {
      preLoaderRoute: typeof LayoutApplicationsIndexImport
      parentRoute: typeof LayoutApplicationsImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  LayoutRoute.addChildren([
    LayoutAdminRoute,
    LayoutApplicationsRoute.addChildren([
      LayoutApplicationsApplicationIdRoute,
      LayoutApplicationsIndexRoute,
    ]),
    LayoutJobsRoute,
    LayoutResumesRoute,
    LayoutScreensRoute,
    LayoutSettingsRoute,
    LayoutIndexRoute,
    LayoutJobJobIdRoute,
  ]),
  LoginRoute,
  RecoverPasswordRoute,
  ResetPasswordRoute,
  SignupRoute,
])

/* prettier-ignore-end */
